IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'SP')
INSERT INTO UFs (Sigla, Nome)
VALUES ('SP', 'São Paulo');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'AC')
INSERT INTO UFs VALUES ('AC','Acre');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'AL')
INSERT INTO UFs VALUES ('AL','Alagoas');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'AP')
INSERT INTO UFs VALUES ('AP','Amapá');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'AM')
INSERT INTO UFs VALUES ('AM','Amazonas');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'BA')
INSERT INTO UFs VALUES ('BA','Bahia');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'CE')
INSERT INTO UFs VALUES ('CE','Ceará');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'DF')
INSERT INTO UFs VALUES ('DF','Distrito Federal');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'ES')
INSERT INTO UFs VALUES ('ES','Espírito Santo');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'GO')
INSERT INTO UFs VALUES ('GO','Goiás');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'MA')
INSERT INTO UFs VALUES ('MA','Maranhão');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'MT')
INSERT INTO UFs VALUES ('MT','Mato Grosso');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'MS')
INSERT INTO UFs VALUES ('MS','Mato Grosso do Sul');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'MG')
INSERT INTO UFs VALUES ('MG','Minas Gerais');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'PA')
INSERT INTO UFs VALUES ('PA','Pará');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'PB')
INSERT INTO UFs VALUES ('PB','Paraíba');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'PR')
INSERT INTO UFs VALUES ('PR','Paraná');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'PE')
INSERT INTO UFs VALUES ('PE','Pernambuco');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'PI')
INSERT INTO UFs VALUES ('PI','Piauí');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'RJ')
INSERT INTO UFs VALUES ('RJ','Rio de Janeiro');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'RN')
INSERT INTO UFs VALUES ('RN','Rio Grande do Norte');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'RS')
INSERT INTO UFs VALUES ('RS','Rio Grande do Sul');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'RO')
INSERT INTO UFs VALUES ('RO','Rondônia');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'RR')
INSERT INTO UFs VALUES ('RR','Roraima');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'SC')
INSERT INTO UFs VALUES ('SC','Santa Catarina');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'SP')
INSERT INTO UFs VALUES ('SP','São Paulo');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'SE')
INSERT INTO UFs VALUES ('SE','Sergipe');

IF NOT EXISTS (SELECT 1 FROM UFs WHERE Sigla = 'TO')
INSERT INTO UFs VALUES ('TO','Tocantins');